### ISSUE TITLE
"Hide hearts..." option doesn't work for pets

### ISSUE THREAD

**Issue by DespairScent** [urbanyeti/stardew-better-ranching#21] opened 2024-04-21 06:29 UTC
Despite "Hide hearts..." option enabled and my pet has full friendship, I can still see the heart bubble above.

**Comment by DespairScent** [comment] 2024-04-21 06:36
Considering that there are “pet gifts”, I think it’s worth adding a separate option that would hide hearts specifically for pets with full friendship.

**Comment by urbanyeti** [comment] 2024-04-29 15:47
Just to be clear, are you saying that your pet has max friendship and you have the "Hides the hearts when friendship with an animal or pet is at maximum level" enabled but the bubbles are still showing?

If so, I'll need to see if I can reproduce this.

As a separate feature enhancement, I like your idea of splitting up the options to hide bubbles for max friendship into different options for animals and pets, but I might actually just add an option to see if your pet has a gift for you if possible.

**Comment by DespairScent** [comment] 2024-04-30 07:25
The error is here: https://github.com/urbanyeti/stardew-better-ranching/blob/9a460c71b16e90ed2820ea1c5cdfb9fec63d0f3d/BetterRanching/BetterRanchingApi.cs#L22

```tryGetFriendshipLevelForNPC()``` does not return the animal's friendship level.

**Comment by urbanyeti** [comment] 2024-04-30 18:53
That makes a lot of sense! It probably behaves differently because the "Name" value for the pets is variable so the friendship level needs to be looked up differently. I wonder if this has always been how it behavior for that method and nobody noticed this bug in my mod before, or if this could be a small bug in Stardew Valley from the 1.6 refactor.

Either way, thank you-- I'm on it! Let me look through the game code and look for an alternate way to get the value.

**Comment by urbanyeti** [comment] 2024-04-30 19:40
Alright! I figured out how to correctly get the friendship level for pets and have a fix. Working on another issue and then will push it out.

**Comment by urbanyeti** [comment] 2024-04-30 22:22
Fix is in new version (now on nexus). Thanks for figuring this one out!

**Closed as completed by urbanyeti** 2024-04-30 22:22 UTC
